# Acid Gas -- imported from Schism Tracker palettes.c
Background:      #868600
Highlight:       #FFFF00
Lowlight:        #00FF00
Text:            #083508
Data:            #FFFF55
Black:           #083508
EditText:        #080004
EditBG:          #083508
EditBGlow:       #18752D
EditBGhigh:      #418649
Brighttext:      #080004
SelectedBGLow:   #5D756D
SelectedBGHigh:  #696900
LCDHigh:         #FFFF55
LCDMid:          #2D7D39
LCDLow:          #205500
CursorRowHigh:   #FFFF04
CursorRowLow:    #35312D
