# Atlantic -- imported from Schism Tracker palettes.c
Background:      #080079
Highlight:       #55AEFF
Lowlight:        #2049AE
Text:            #000000
Data:            #6D82FF
Black:           #000000
EditText:        #A2A2A2
EditBG:          #000000
EditBGlow:       #000092
EditBGhigh:      #004982
Brighttext:      #A2A2A2
SelectedBGLow:   #49D2FF
SelectedBGHigh:  #55CA55
LCDHigh:         #6D82FF
LCDMid:          #00248A
LCDLow:          #000079
CursorRowHigh:   #28416D
CursorRowLow:    #202D4D
