# Camouflage (default) -- imported from Schism Tracker palettes.c
Background:      #7D5945
Highlight:       #EBEBCA
Lowlight:        #B69679
Text:            #000000
Data:            #FFFF55
Black:           #000000
EditText:        #DFEBE3
EditBG:          #000000
EditBGlow:       #18752D
EditBGhigh:      #399E75
Brighttext:      #DFEBE3
SelectedBGLow:   #A2A2A2
SelectedBGHigh:  #8E1455
LCDHigh:         #FFFF55
LCDMid:          #288A51
LCDLow:          #205500
CursorRowHigh:   #59413D
CursorRowLow:    #35312D
