# FX 2.0 -- imported from Schism Tracker palettes.c
Background:      #183920
Highlight:       #DFE7CA
Lowlight:        #798282
Text:            #001000
Data:            #4DAE4D
Black:           #001000
EditText:        #71AAAE
EditBG:          #001000
EditBGlow:       #4D205D
EditBGhigh:      #399E75
Brighttext:      #71AAAE
SelectedBGLow:   #31CE8E
SelectedBGHigh:  #31DF7D
LCDHigh:         #4DAE4D
LCDMid:          #416169
LCDLow:          #61315D
CursorRowHigh:   #143D10
CursorRowLow:    #0C351C
