# Gold -- imported from Schism Tracker palettes.c
Background:      #514528
Highlight:       #FFDF86
Lowlight:        #A69255
Text:            #000000
Data:            #49D749
Black:           #000000
EditText:        #C2C6BA
EditBG:          #000000
EditBGlow:       #0000AA
EditBGhigh:      #A69255
Brighttext:      #C2C6BA
SelectedBGLow:   #B2B2B2
SelectedBGHigh:  #55CA55
LCDHigh:         #49D749
LCDMid:          #514982
LCDLow:          #000082
CursorRowHigh:   #49413D
CursorRowLow:    #312D28
