# Gold (Vintage) -- imported from Schism Tracker palettes.c
Background:      #514528
Highlight:       #FFDF86
Lowlight:        #A69255
Text:            #000000
Data:            #00B200
Black:           #000000
EditText:        #C2C6BA
EditBG:          #000000
EditBGlow:       #183175
EditBGhigh:      #A69255
Brighttext:      #C2C6BA
SelectedBGLow:   #B2B2B2
SelectedBGHigh:  #00B200
LCDHigh:         #00B200
LCDMid:          #616165
LCDLow:          #142459
CursorRowHigh:   #49413D
CursorRowLow:    #312D28
