# Hotdog Stand -- imported from Schism Tracker palettes.c
Background:      #000000
Highlight:       #FF0000
Lowlight:        #FFFF00
Text:            #000000
Data:            #FF0000
Black:           #000000
EditText:        #FF0000
EditBG:          #000000
EditBGlow:       #FF0000
EditBGhigh:      #FFFF00
Brighttext:      #FF0000
SelectedBGLow:   #FFFF00
SelectedBGHigh:  #FF0000
LCDHigh:         #FF0000
LCDMid:          #FF8200
LCDLow:          #FFFF00
CursorRowHigh:   #FF0000
CursorRowLow:    #000000
