# Industrial -- imported from Schism Tracker palettes.c
Background:      #494949
Highlight:       #CECECE
Lowlight:        #717171
Text:            #000000
Data:            #DFAE00
Black:           #000000
EditText:        #5D10AE
EditBG:          #000000
EditBGlow:       #350024
EditBGhigh:      #006161
Brighttext:      #5D10AE
SelectedBGLow:   #418261
SelectedBGHigh:  #920000
LCDHigh:         #DFAE00
LCDMid:          #183141
LCDLow:          #390039
CursorRowHigh:   #391C08
CursorRowLow:    #082839
