# Kawaii -- imported from Schism Tracker palettes.c
Background:      #FFD7F3
Highlight:       #492845
Lowlight:        #CE9ABE
Text:            #F7F3FF
Data:            #558ACA
Black:           #F7F3FF
EditText:        #E7C2EF
EditBG:          #F7F3FF
EditBGlow:       #CEC2FF
EditBGhigh:      #B675B2
Brighttext:      #E7C2EF
SelectedBGLow:   #8A4982
SelectedBGHigh:  #CAAAFF
LCDHigh:         #558ACA
LCDMid:          #C29ADB
LCDLow:          #C2DFFF
CursorRowHigh:   #CAD7F3
CursorRowLow:    #FFEBE3
