# Light Blue -- imported from Schism Tracker palettes.c
Background:      #2865B6
Highlight:       #CEEBFF
Lowlight:        #79A2DF
Text:            #000000
Data:            #55FF55
Black:           #000000
EditText:        #CEEBFF
EditBG:          #000000
EditBGlow:       #0000AA
EditBGhigh:      #79A2DF
Brighttext:      #CEEBFF
SelectedBGLow:   #B2B2B2
SelectedBGHigh:  #55FF55
LCDHigh:         #55FF55
LCDMid:          #3D51C2
LCDLow:          #000082
CursorRowHigh:   #49413D
CursorRowLow:    #312D28
