# Midnight Tracking -- imported from Schism Tracker palettes.c
Background:      #002041
Highlight:       #4171C2
Lowlight:        #004D82
Text:            #000000
Data:            #00C292
Black:           #000000
EditText:        #A2A2A2
EditBG:          #000000
EditBGlow:       #000082
EditBGhigh:      #004982
Brighttext:      #A2A2A2
SelectedBGLow:   #828282
SelectedBGHigh:  #710061
LCDHigh:         #00C292
LCDMid:          #002482
LCDLow:          #000061
CursorRowHigh:   #103551
CursorRowLow:    #181C2D
