# Pine Colours -- imported from Schism Tracker palettes.c
Background:      #084135
Highlight:       #CEEBFF
Lowlight:        #558275
Text:            #000000
Data:            #D2CE86
Black:           #000000
EditText:        #EBEB86
EditBG:          #000000
EditBGlow:       #490061
EditBGhigh:      #79A2DF
Brighttext:      #EBEB86
SelectedBGLow:   #B2B2B2
SelectedBGHigh:  #C69E55
LCDHigh:         #D2CE86
LCDMid:          #6151A2
LCDLow:          #312841
CursorRowHigh:   #353D39
CursorRowLow:    #392D39
