# Purple Motion -- imported from Schism Tracker palettes.c
Background:      #392839
Highlight:       #826982
Lowlight:        #614961
Text:            #000000
Data:            #82FF82
Black:           #000000
EditText:        #826982
EditBG:          #000000
EditBGlow:       #2D2D55
EditBGhigh:      #614961
Brighttext:      #826982
SelectedBGLow:   #C2C2C2
SelectedBGHigh:  #008200
LCDHigh:         #82FF82
LCDMid:          #493959
LCDLow:          #202041
CursorRowHigh:   #313539
CursorRowLow:    #24282D
