# Soundtracker -- imported from Schism Tracker palettes.c
Background:      #496171
Highlight:       #CEE3F3
Lowlight:        #8EAABE
Text:            #000000
Data:            #55FF59
Black:           #000000
EditText:        #CEEBFF
EditBG:          #000000
EditBGlow:       #9641FB
EditBGhigh:      #6DA2DF
Brighttext:      #CEEBFF
SelectedBGLow:   #B2B2B2
SelectedBGHigh:  #55FF55
LCDHigh:         #55FF59
LCDMid:          #8271EB
LCDLow:          #82359A
CursorRowHigh:   #494145
CursorRowLow:    #353935
