# Volcanic -- imported from Schism Tracker palettes.c
Background:      #652400
Highlight:       #CE5D00
Lowlight:        #A23900
Text:            #000000
Data:            #009E14
Black:           #000000
EditText:        #FB7D00
EditBG:          #000000
EditBGlow:       #710000
EditBGhigh:      #828282
Brighttext:      #FB7D00
SelectedBGLow:   #A2A2A2
SelectedBGHigh:  #00719A
LCDHigh:         #009E14
LCDMid:          #794141
LCDLow:          #550000
CursorRowHigh:   #28416D
CursorRowLow:    #202D4D
