# Why Colors? -- imported from Schism Tracker palettes.c
Background:      #243941
Highlight:       #FFFFFF
Lowlight:        #497582
Text:            #000000
Data:            #FFFF82
Black:           #000000
EditText:        #619AB6
EditBG:          #000000
EditBGlow:       #515151
EditBGhigh:      #828282
Brighttext:      #619AB6
SelectedBGLow:   #C2C2C2
SelectedBGHigh:  #FFFF82
LCDHigh:         #FFFF82
LCDMid:          #696969
LCDLow:          #282828
CursorRowHigh:   #515151
CursorRowLow:    #282828
